apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-deployer
rules:
- apiGroups: ["", "apps", "batch", "extensions", "route.openshift.io", "image.openshift.io", "project.openshift.io", "template.openshift.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-deployer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-deployer
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: default